services:
  db:
    image: mariadb:10.6
    container_name: pg-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toss_pg
      MYSQL_USER: toss
      MYSQL_PASSWORD: toss1234
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - toss-net

  spring-api:
    build: ./spring-api
    container_name: spring-api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - TOSS_SECRET_KEY=${TOSS_SECRET_KEY}
      - TOSS_SECURITY_KEY=${TOSS_SECURITY_KEY}
    networks:
      - toss-net

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - spring-api
    networks:
      - toss-net


networks:
  toss-net:
    driver: bridge

volumes:
  db-data: