version: "3"

services:
  spring-api:
    build: ./spring-api
    container_name: spring-api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - toss-net

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - spring-api
    networks:
      - toss-net

networks:
  toss-net:
    driver: bridge
